### ISSUE TITLE
Test Cases Order are random

### ISSUE THREAD

**Issue by leoGalani** [leoGalani/sherlock#3]
Test cases are in a dict, been created at random position.

**Comment by aechiara** [comment]
how it should be ? ordered by date of creation ? alphabetically ?

**Comment by leoGalani** [comment]
the inputs have incremental number on their id.

First I nedd to fix the javascript method that include the inputs in the interface, so the first input respect the pattern.

**Comment by leoGalani** [comment]
fixed
