### ISSUE TITLE
Add Portuguese Translation to the documentation

### ISSUE THREAD

**Issue by leoGalani** [leoGalani/sherlock#37]
Add Portuguese Translation to the documentation.

Tasks: 
 - Translate read the docs and refined as needed
 - http://docs.readthedocs.io/en/latest/localization.html

Obligatory: Falar português Brasileiro ( Automatic translations will not be accepted)

**Comment by rafa-acioly** [comment]
i can do this! :smile:

**Comment by cacahds** [comment]
Can I get this one?
