### ISSUE TITLE
Protractor Flow Tests

### ISSUE THREAD

**Issue by leoGalani** [leoGalani/sherlock#38]
The project lacks an end-to-end interface test.

It needs an easy to trigger and maintain tests scripts.

Please don't make core changes on others initial setup unless both parts agree.

**Comment by MarcosVCCruz** [comment]
I'm starting this issue, probably until 21/11/2017, it will be ready :)

**Comment by MarcosVCCruz** [comment]
Hi, here is the beta version from automated E2E test in Sherlock Qa
https://github.com/MarcosVCCruz/AutomationSherlockQa
I will be improving the project soon
