### ISSUE TITLE
Edição de Scenario não adiciona mais cases

### ISSUE THREAD

**Issue by edutoporoski** [leoGalani/sherlock#6]
Galani,
Segue a descrição de uma falha encontrada na edição de Scenarios:

Como Ocorre?
- Ao entrar na opção "Edit Scenarios and Cases" e clicar em "Add more cases" não é possivel adicionar mais Cases em um cenario já criado. Ele solicita como campo obrigatorio o nome do Scenario, e mesmo inserindo o mesmo nome ele duplica o Scenario.
- Project  utilizado "Toporoski Tests"

**Comment by leoGalani** [comment]
Hmm.. Isso não é um bug .. É falta de funcionalidade mesmo :( 
Só esta dando para adicionar novos cenários + cases... e não criar novos cases para um cenário..

Vlw.. ! Colocando no roadmap.

**Comment by leoGalani** [comment]
Feito na nova versão :)

Será disponibilizada em breve
